version: '3'

services:
  postgres:
    image: "postgres:9.6"
    environment:
      - POSTGRES_DB=file_downloader
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
